export { default as HomeLayout } from './HomeLayout'
export { default as AuthLayout} from './AuthLayout'
export { default as Landing } from './Landing'
export { default as Error } from './Error'
export { default as Chat } from './Chat'
export { default as Login } from './Login'
export { default as Signup } from './Signup'
export { default as Profile } from './Profile'
export { default as Diagnosis } from './Diagnosis'
export { default as DashboardLayout } from './DashboardLayout'
export { default as ForgotPassword } from  './ForgotPassword'
export { default as VerificationPage} from './VerificationPage'
